### PR TITLE
Fix build, remove local git2

### PR DESCRIPTION
**Pull request by JadedCtrl**

### CODE REVIEW

**Comment by scottmc** [comment]
As you touch files for this, please update the headers to follow Haiku's coding guidelines, see #1

**Comment by JadedCtrl** [comment]
Reformatted them, thanks. I've never seen doxygen-style headers in a Haiku project, I assume we can just keep them separated with a newline in the same comment (like with an "Authors:" section)?

**Comment by pulkomandy** [comment]
The Doxygen headers do not look like they have a lot of useful info here.

In Haiku we use Doxygen comments on functions to document the Haiku internals (but no tool is used to extract these, and it is generally not done very often).

The API reference is built using Doxygen, but the sources for that are stored separately from the .cpp/.h files.

**Comment by JadedCtrl** [comment]
Context is pretty explanatory for the headers, yea. So just removing @file and @brief might be right move here?

**Comment by pulkomandy** [comment]
@file with just the filename is completely useless, and @brief can be converted to a normal comment, in case people find the filename not clear enough to guess what a file is doing.

**Comment by JadedCtrl** [comment]
Alright, just removed the doxygen headers.

**Pull request merged**
